@baseUrl = http://localhost:3000
@contentType = application/json

GET {{baseUrl}}/movies
###
POST {{baseUrl}}/movies

{
    "id": 10,
    "name": "a",
    "ratings": 0,
    "genre": "Action"
}

###
GET {{baseUrl}}/movies/1
###
PATCH {{baseUrl}}/movies/1

{
    "ratings": 5

}
###
DELETE {{baseUrl}}/movies/1

###
GET {{baseUrl}}/movies?query=john